sudo pip install Django
sudo pip install south
sudo pip install psycopy2
sudo pip install stratum
sudo pip install path.py
sudo pip install pelican
sudo pip install sh
sudo pip install slimit
sudo pip install slimmer
sudo pip install watchdog
sudo pip install pyquery
